stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git config --global user.email "scotmarvin@gmail.com"
    - git config --global user.name "Scot Marvin"
    - git clone --depth=1 --branch=main https://github.com/$GITHUB_REPO.git github_repo
    - cd github_repo
    - git remote set-url origin https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
    - git pull origin main
    - cp -r ../* .  # copy the contents from GitLab to GitHub repo
    - git add .
    - git commit -m "GitLab CI update"
    - git push origin main
  only:
    - main  # or the branch you want to sync with GitHub
